mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # ????????????????????????????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.166.8:3306/ry?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: zhourui
    password: zhourui123
he: xxxx
